testing environment and other fixes and logging

diff --git a/run b/run
--- a/run
+++ b/run
@@ -5,15 +5,26 @@ if ! command -v tsc &> /dev/null; then
     echo "TypeScript is not installed. Please install it first."
     exit 1
 fi
-rm metrics.db
+# rm metrics.db
 # Compile TypeScript files
 # echo "Compiling TypeScript..."
+
+export GITHUB_TOKEN=
+export LOG_FILE=logfile.txt
+export LOG_LEVEL=1
+
+# echo $GITHUB_TOKEN
+# echo $LOG_FILE
+# echo $LOG_LEVEL
 if [ "$1" == "install" ]; then
     npm install --save better-sqlite3 commander axios dotenv isomorphic-git
-    npm install --save-dev typescript @types/better-sqlite3 @types/commander 
+    npm install --save-dev typescript @types/better-sqlite3 @types/commander @types/node@18.11.9 jest ts-jest @types/jest
     # tsc main.ts || { echo "Compilation failed"; exit 1; }
 elif [ -f "$1" ]; then
-    # tsc || { echo "Compilation failed"; exit 1; }
+    tsc || { echo "Compilation failed"; exit 1; }
+    # tsc
+elif [ "$1" == "test" ]; then
+    # echo "Here"
     tsc
 else
     echo "Usage: ./run install or ./run URL_FILE or ./run test"
@@ -26,10 +37,11 @@ fi
 #     echo "Running the program with 'install' command..."
 #     node main.js install || { echo "Failed to run the program with 'install'"; exit 1; }
 if [ "$1" == "test" ]; then
-    echo "Testing"
+    # echo "Testing"
     node main.js test || { echo "Failed to run the program with 'test'"; exit 1; }
 elif [ -f "$1" ]; then
-    echo "Processing file: $1"
+    # echo "Processing file: $1"
     # Run your compiled TypeScript program with the provided file as an argument
     node main.js process "$1" || { echo "Failed to run the program"; exit 1; }
+    rm metrics.db
 fi
